# Set to true to add reviewers to pull requests
addReviewers: true
addAssignees: author

numberOfReviewers: 1

useReviewGroups: true

reviewGroups:
  groupA:
    - takaheraw

useAssigneeGroups: false

filterLabels:
  # Run
  include:
    - dependencies
  # Not run
  exclude:
    - javascript
