version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Japan
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: sidekiq-unique-jobs
    versions:
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.6
    - 7.0.7
    - 7.0.8
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.1
  - dependency-name: sidekiq
    versions:
    - 6.1.3
    - 6.2.0
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 4.1.1
    - 5.0.0
  - dependency-name: webmock
    versions:
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: config
    versions:
    - 2.2.3
    - 3.0.0
  - dependency-name: rails
    versions:
    - 6.0.3.5
  - dependency-name: redis-namespace
    versions:
    - 1.8.1
  - dependency-name: shoulda-matchers
    versions:
    - 4.5.1
  - dependency-name: committee
    versions:
    - 4.3.0
  - dependency-name: active_model_serializers
    versions:
    - 0.10.12
  - dependency-name: puma
    versions:
    - 4.3.7
  - dependency-name: active_decorator
    versions:
    - 1.3.4
  - dependency-name: bullet
    versions:
    - 6.1.3
  - dependency-name: derailed_benchmarks
    versions:
    - 2.0.1
  - dependency-name: better_errors
    versions:
    - 2.9.1
  - dependency-name: database_cleaner
    versions:
    - 2.0.1
  - dependency-name: jbuilder
    versions:
    - 2.11.2
  - dependency-name: bootsnap
    versions:
    - 1.7.2
  - dependency-name: simplecov
    versions:
    - 0.21.2
  - dependency-name: binding_of_caller
    versions:
    - 1.0.0
  - dependency-name: faker
    versions:
    - 2.15.1
  - dependency-name: airbrake
    versions:
    - 10.0.6
  - dependency-name: webpacker
    versions:
    - 5.2.1
  - dependency-name: bundler-audit
    versions:
    - 0.7.0.1
