version: 2.1
orbs:
  ganta-git: ganta/git@1.2.0
jobs:
  build:
    parallelism: 1
    working_directory: ~/circleci-suburi

    docker:
      - image: circleci/ruby:2.6.3-node
      - image: circleci/mysql:8.0.12
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_ROOT_PASSWORD: ''
      - image: redis

    steps:

      - ganta-git/shallow-clone-checkout

      - run:
          name: Install system dependencies
          command: |
            gem install bundler -v 2.0.1

      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "Gemfile.lock" }}
            - bundle-cache-

      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle

      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: A static analysis security
          command: bundle exec brakeman -z

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run:
          name: create test DB
          environment:
            RAILS_ENV: test
            DATABASE_USER: root
          command: |
            mv config/database.ci.yml config/database.yml
            bin/rails db:create
            bin/rails db:setup

      - run:
          name: Install tbls
          command: |
            curl -sL https://git.io/use-tbls > use-tbls.tmp && . ./use-tbls.tmp && rm ./use-tbls.tmp
            tbls diff my://root@127.0.0.1:3306/suburi_development doc/schema

      - run:
          name: Generate swagger ui
          command: |
            ruby bin/swagger.rb

      - run: mkdir ~/rspec

      - run:
          name: run test
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml --exclude-pattern "spec/integration/**/*_spec.rb"
          when: always

      - store_test_results:
          path: ~/rspec

      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
