version: 2.1

orbs:
  ganta-git: ganta/git@1.2.0

executors:
  default:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.6.3-node
        environment:
          BUNDLER_VERSION: 2.1.4
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          DATABASE_USER: root
      - image: circleci/mysql:8.0.12
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_ROOT_PASSWORD: ''
      - image: redis

commands:
  restore_repo:
    steps:
      - restore_cache:
          name: restore repo
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
  restore_bundle_dependencies:
    steps:
      - restore_cache:
          name: restore bundle
          keys:
            - bundle-v2-cache-{{ checksum "Gemfile.lock" }}
            - bundle-v2-cache-
      - run:
          name: gem install bundler
          command: |
            gem install bundler
      - run:
          name: bundle install
          command: bundle check || bundle install
  setup_db:
    steps:
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: create test DB
          command: |
            mv config/database.ci.yml config/database.yml
            bin/rails db:create
            bin/rails db:setup

jobs:
  build:
    executor:
      name: default
    steps:
      # source
      - ganta-git/shallow-clone-checkout
      - save_cache:
          name: save repo
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app
      # bundle
      - restore_bundle_dependencies
      - save_cache:
          name: save bundle
          key: bundle-v2-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # yarn
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run:
          name: yarn install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  rubocop:
    executor:
      name: default
    steps:
      - restore_repo
      - restore_bundle_dependencies
      - run:
          name: RuboCop
          command: bundle exec rubocop
  brakeman:
    executor:
      name: default
    steps:
      - restore_repo
      - restore_bundle_dependencies
      - run:
          name: A static analysis security
          command: bundle exec brakeman -z
  precompile:
    executor:
      name: default
    steps:
      - restore_repo
      - restore_bundle_dependencies
      - run:
          name: Precompile assets
          command: bundle exec rake assets:precompile
  tbls:
    executor:
      name: default
    steps:
      - restore_repo
      - restore_bundle_dependencies
      - setup_db
      - run:
          name: Install tbls
          command: |
            curl -sL https://git.io/use-tbls > use-tbls.tmp && TBLS_VERSION=v1.39.0 . ./use-tbls.tmp && rm ./use-tbls.tmp
            echo `tbls version`
            tbls diff my://root@127.0.0.1:3306/suburi_test
  swagger:
    executor:
      name: default
    steps:
      - restore_repo
      - restore_bundle_dependencies
      - run:
          name: Generate swagger ui
          command: |
            ruby bin/swagger.rb
      - store_artifacts:
          path: swagger-ui/dist
  test:
    parallelism: 3
    executor:
      name: default
    steps:
      - restore_repo
      - restore_bundle_dependencies
      - setup_db
      - run:
          name: run test
          command: |
            mkdir /tmp/test-results
            TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=filesize)
            bundle exec rspec $TESTFILES --profile 10 --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format progress
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - rubocop:
          requires:
            - build
      - brakeman:
          requires:
            - build
      - tbls:
          requires:
            - build
      - swagger:
          requires:
            - build
      - test:
          requires:
            - build
