name: "Auto Assign PR Reviewers"

on:
  pull_request:

jobs:
  add-reviews:
    if: startsWith(github.event.pull_request.head.ref, 'dependabot/bundler/')
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yml"
