name: "Auto Assign PR Reviewers"

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
