name: "Auto Assign PR Reviewers"

on:
  pull_request:
    branches:
      - 'dependabot/**'

jobs:
  # Automatically assigns reviewers and owner
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/auto_assign.yml"
